services:
    db:
        image: postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_HOST=localhost
            - POSTGRES_USER=dev
            - POSTGRES_DB=teste
            - POSTGRES_PASSWORD=123456
        container_name: database
        restart: always