import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { config } from '@fortawesome/fontawesome-svg-core';
import { CSSProperties } from 'react';

config.autoAddCss = false;

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const style: CSSProperties = {
    background: 'rgb(41,37,37)',
    color: 'rgba(255,255,255,0.5)',
    margin: '0',
    padding: '0',
    clipPath: 'inset(0)',
    overflow: 'hidden',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body style={style} className={inter.className}>
                {children}
            </body>
        </html>
    );
}
